const THEMES_DATA = [
  {
    "id": "afrique",
    "title": "PAYS D'AFRIQUE",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de pays du continent africain.",
    "answers": [
      "Afrique du Sud",
      "Algérie",
      "Angola",
      "Bénin",
      "Botswana",
      "Burkina Faso",
      "Burundi",
      "Cameroun",
      "Cap-Vert",
      "Centrafrique",
      "Comores",
      "Congo",
      "Côte d'Ivoire",
      "Djibouti",
      "Égypte",
      "Érythrée",
      "Éthiopie",
      "Gabon",
      "Gambie",
      "Ghana",
      "Guinée",
      "Kenya",
      "Libye",
      "Madagascar",
      "Mali",
      "Maroc",
      "Mauritanie",
      "Mozambique",
      "Niger",
      "Nigeria",
      "Ouganda",
      "Rwanda",
      "Sénégal",
      "Somalie",
      "Soudan",
      "Tanzanie",
      "Tchad",
      "Togo",
      "Tunisie",
      "Zambie",
      "Zimbabwe"
    ]
  },
  {
    "id": "amerique_latine",
    "title": "PAYS D'AMÉRIQUE LATINE",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de pays d'Amérique latine.",
    "answers": [
      "Mexique",
      "Guatemala",
      "Belize",
      "Honduras",
      "Salvador",
      "Nicaragua",
      "Costa Rica",
      "Panama",
      "Cuba",
      "Haïti",
      "République Dominicaine",
      "Jamaïque",
      "Venezuela",
      "Colombie",
      "Équateur",
      "Pérou",
      "Brésil",
      "Bolivie",
      "Paraguay",
      "Uruguay",
      "Argentine",
      "Chili",
      "Guyana",
      "Suriname"
    ]
  },
  {
    "id": "animaux_fr",
    "title": "ANIMAUX DE LA FERME",
    "icon": "../assets/Images/animaux.png",
    "question": "Citez un maximum d'animaux qu'on trouve traditionnellement dans une ferme.",
    "answers": [
      "Vache",
      "Cochon",
      "Mouton",
      "Chèvre",
      "Poulet",
      "Poule",
      "Coq",
      "Canard",
      "Oie",
      "Dinde",
      "Lapin",
      "Cheval",
      "Âne",
      "Mule",
      "Bœuf",
      "Taureau",
      "Veau",
      "Agneau",
      "Cabri",
      "Chien",
      "Chat",
      "Pigeon",
      "Pintade",
      "Caille",
      "Faisan",
      "Abeille",
      "Ver à soie",
      "Porc",
      "Truie",
      "Poney"
    ]
  },
  {
    "id": "artistes_fr",
    "title": "CHANTEURS / ARTISTES FRANÇAIS",
    "icon": "../assets/Images/musique.png",
    "question": "Citez un maximum d'artistes ou chanteurs français (solo ou groupe).",
    "answers": [
      "Édith Piaf",
      "Charles Aznavour",
      "Serge Gainsbourg",
      "Jacques Brel",
      "Barbara",
      "Jean-Jacques Goldman",
      "Johnny Hallyday",
      "Claude François",
      "Michel Sardou",
      "Renaud",
      "Francis Cabrel",
      "Vanessa Paradis",
      "Stromae",
      "Angèle",
      "Aya Nakamura",
      "Jul",
      "Orelsan",
      "Maître Gims",
      "Soprano",
      "Nekfeu",
      "PNL",
      "Indochine",
      "M",
      "Zazie",
      "IAM",
      "NTM",
      "Daft Punk",
      "Air",
      "Christine and the Queens",
      "Vald",
      "Damso"
    ]
  },
  {
    "id": "capitales_eu",
    "title": "CAPITALES EUROPÉENNES",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de capitales de pays européens.",
    "answers": [
      "Paris",
      "Berlin",
      "Madrid",
      "Rome",
      "Vienne",
      "Varsovie",
      "Bucarest",
      "Budapest",
      "Prague",
      "Sofia",
      "Bruxelles",
      "Amsterdam",
      "Stockholm",
      "Oslo",
      "Copenhague",
      "Helsinki",
      "Lisbonne",
      "Athènes",
      "Dublin",
      "Zagreb",
      "Bratislava",
      "Ljubljana",
      "Tallinn",
      "Riga",
      "Vilnius",
      "Sarajevo",
      "Belgrade",
      "Podgorica",
      "Tirana",
      "Skopje",
      "Reykjavik",
      "Kiev",
      "Minsk",
      "Moscou",
      "Berne",
      "Luxembourg",
      "La Valette"
    ]
  },
  {
    "id": "ciup",
    "title": "MAISONS DE LA CIUP",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de maisons de la Cité Internationale Universitaire de Paris.",
    "answers": [
      "Fondation Deutsch de la Meurthe",
      "Maison Internationale",
      "Maison des Provinces de France",
      "Maison du Maroc",
      "Maison de la Tunisie",
      "Maison du Cambodge",
      "Maison du Liban",
      "Maison de l'Inde",
      "Maison du Japon",
      "Maison du Brésil",
      "Maison de la Suède",
      "Maison de la Suisse",
      "Maison de la Norvège",
      "Maison du Portugal",
      "Collège Néerlandais",
      "Maison des États-Unis",
      "Maison de l'Allemagne",
      "Maison de la Corée",
      "Maison de l'Argentine",
      "Maison du Mexique",
      "Maison du Canada",
      "Maison des Étudiants de la Francophonie",
      "Maison de l'Île-de-France",
      "Maison de l'Italie"
    ]
  },
  {
    "id": "departements",
    "title": "DÉPARTEMENTS FRANÇAIS",
    "icon": "../assets/Images/histoire.png",
    "question": "Citez un maximum de départements français (par leur nom).",
    "answers": [
      "Ain",
      "Aisne",
      "Allier",
      "Alpes-Maritimes",
      "Ardèche",
      "Ardennes",
      "Ariège",
      "Aube",
      "Aude",
      "Aveyron",
      "Bouches-du-Rhône",
      "Calvados",
      "Cantal",
      "Charente",
      "Cher",
      "Corrèze",
      "Corse",
      "Côte-d'Or",
      "Côtes-d'Armor",
      "Creuse",
      "Dordogne",
      "Doubs",
      "Drôme",
      "Essonne",
      "Eure",
      "Finistère",
      "Gard",
      "Gers",
      "Gironde",
      "Hérault",
      "Ille-et-Vilaine",
      "Indre",
      "Isère",
      "Jura",
      "Landes",
      "Loire",
      "Loire-Atlantique",
      "Loiret",
      "Lozère",
      "Maine-et-Loire",
      "Manche",
      "Marne",
      "Mayenne",
      "Moselle",
      "Nièvre",
      "Nord",
      "Oise",
      "Orne",
      "Pas-de-Calais",
      "Puy-de-Dôme",
      "Rhône",
      "Saône-et-Loire",
      "Sarthe",
      "Savoie",
      "Paris",
      "Seine-Maritime",
      "Seine-et-Marne",
      "Yvelines",
      "Somme",
      "Tarn",
      "Var",
      "Vaucluse",
      "Vendée",
      "Vienne",
      "Vosges",
      "Yonne",
      "Hauts-de-Seine",
      "Seine-Saint-Denis",
      "Val-de-Marne",
      "Val-d'Oise"
    ]
  },
  {
    "id": "europe",
    "title": "PAYS D'EUROPE",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de pays du continent européen.",
    "answers": [
      "Albanie",
      "Allemagne",
      "Andorre",
      "Autriche",
      "Belgique",
      "Biélorussie",
      "Bosnie-Herzégovine",
      "Bulgarie",
      "Chypre",
      "Croatie",
      "Danemark",
      "Espagne",
      "Estonie",
      "Finlande",
      "France",
      "Grèce",
      "Hongrie",
      "Irlande",
      "Islande",
      "Italie",
      "Kosovo",
      "Lettonie",
      "Liechtenstein",
      "Lituanie",
      "Luxembourg",
      "Malte",
      "Moldova",
      "Monaco",
      "Monténégro",
      "Norvège",
      "Pays-Bas",
      "Pologne",
      "Portugal",
      "Roumanie",
      "Royaume-Uni",
      "Russie",
      "Saint-Marin",
      "Serbie",
      "Slovaquie",
      "Slovénie",
      "Suède",
      "Suisse",
      "Tchéquie",
      "Ukraine",
      "Vatican"
    ]
  },
  {
    "id": "films_fr",
    "title": "FILMS FRANÇAIS CULTES",
    "icon": "../assets/Images/cinema.png",
    "question": "Citez un maximum de films français devenus cultes ou iconiques.",
    "answers": [
      "Intouchables",
      "Le Fabuleux Destin d'Amélie Poulain",
      "La Haine",
      "Les Visiteurs",
      "Bienvenue chez les Ch'tis",
      "Léon",
      "Les Choristes",
      "Un Prophète",
      "Le Dîner de Cons",
      "À Bout de Souffle",
      "OSS 117",
      "Nikita",
      "Taxi",
      "La Cité de la Peur",
      "La Grande Vadrouille",
      "Astérix Mission Cléopâtre",
      "Le Grand Bleu",
      "La Vie en Rose",
      "8 Femmes",
      "Trois Hommes et un Couffin",
      "Les Misérables",
      "Au Revoir les Enfants",
      "Le Fabuleux",
      "Banlieue 13",
      "La Vérité si je mens",
      "Qu'est-ce qu'on a fait au Bon Dieu",
      "Le Grand Bain"
    ]
  },
  {
    "id": "g20",
    "title": "PAYS DU G20",
    "icon": "../assets/Images/histoire.png",
    "question": "Citez un maximum de pays membres du G20.",
    "answers": [
      "Afrique du Sud",
      "Allemagne",
      "Arabie Saoudite",
      "Argentine",
      "Australie",
      "Brésil",
      "Canada",
      "Chine",
      "Corée du Sud",
      "États-Unis",
      "France",
      "Inde",
      "Indonésie",
      "Italie",
      "Japon",
      "Mexique",
      "Royaume-Uni",
      "Russie",
      "Turquie",
      "Union Européenne"
    ]
  },
  {
    "id": "grandes_villes_fr",
    "title": "GRANDES VILLES FRANÇAISES",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de grandes villes françaises (communes de +100 000 hab.).",
    "answers": [
      "Paris",
      "Marseille",
      "Lyon",
      "Toulouse",
      "Nice",
      "Nantes",
      "Montpellier",
      "Strasbourg",
      "Bordeaux",
      "Lille",
      "Rennes",
      "Reims",
      "Le Havre",
      "Saint-Étienne",
      "Toulon",
      "Grenoble",
      "Dijon",
      "Angers",
      "Nîmes",
      "Villeurbanne",
      "Saint-Denis",
      "Clermont-Ferrand",
      "Le Mans",
      "Aix-en-Provence",
      "Brest",
      "Tours",
      "Limoges",
      "Amiens",
      "Metz",
      "Besançon"
    ]
  },
  {
    "id": "instruments",
    "title": "INSTRUMENTS DE MUSIQUE",
    "icon": "../assets/Images/musique.png",
    "question": "Citez un maximum d'instruments de musique (tous genres confondus).",
    "answers": [
      "Violon",
      "Alto",
      "Violoncelle",
      "Contrebasse",
      "Guitare",
      "Guitare basse",
      "Mandoline",
      "Banjo",
      "Piano",
      "Orgue",
      "Clavecin",
      "Accordéon",
      "Flûte traversière",
      "Flûte à bec",
      "Hautbois",
      "Clarinette",
      "Saxophone",
      "Basson",
      "Cor",
      "Trompette",
      "Trombone",
      "Tuba",
      "Euphonium",
      "Batterie",
      "Xylophone",
      "Marimba",
      "Vibraphone",
      "Harpe",
      "Luth",
      "Sitar",
      "Kora",
      "Didgeridoo",
      "Balafon",
      "Djembé",
      "Bongo"
    ]
  },
  {
    "id": "jo_sports",
    "title": "SPORTS AUX JO D'ÉTÉ",
    "icon": "../assets/Images/sport.png",
    "question": "Citez un maximum de disciplines présentes aux Jeux Olympiques d'été.",
    "answers": [
      "Athlétisme",
      "Natation",
      "Cyclisme",
      "Judo",
      "Tennis",
      "Football",
      "Basketball",
      "Volleyball",
      "Rugby à 7",
      "Boxe",
      "Lutte",
      "Escrime",
      "Tir",
      "Aviron",
      "Kayak",
      "Canoë",
      "Voile",
      "Équitation",
      "Haltérophilie",
      "Tir à l'arc",
      "Pentathlon moderne",
      "Badminton",
      "Tennis de table",
      "Handball",
      "Water-polo",
      "Plongeon",
      "Natation synchronisée",
      "Trampoline",
      "Golf",
      "Surf",
      "Skateboard",
      "Escalade",
      "Breaking",
      "Taekwondo",
      "Triathlon"
    ]
  },
  {
    "id": "langues",
    "title": "LANGUES LES PLUS PARLÉES",
    "icon": "../assets/Images/histoire.png",
    "question": "Citez un maximum de langues parmi les 30 plus parlées au monde.",
    "answers": [
      "Mandarin",
      "Espagnol",
      "Anglais",
      "Hindi",
      "Arabe",
      "Bengali",
      "Portugais",
      "Russe",
      "Japonais",
      "Punjabi",
      "Malais",
      "Télougou",
      "Marathi",
      "Tamoul",
      "Français",
      "Allemand",
      "Ourdou",
      "Persan",
      "Swahili",
      "Turc",
      "Coréen",
      "Vietnamien",
      "Italien",
      "Polonais",
      "Ukrainien",
      "Néerlandais",
      "Indonésien",
      "Thaï",
      "Birman",
      "Gujarati"
    ]
  },
  {
    "id": "ligne1",
    "title": "ARRÊTS LIGNE 1 DU MÉTRO",
    "icon": "../assets/Images/geographie.png",
    "question": "Citez un maximum d'arrêts de la ligne 1 du métro (La Défense — Château de Vincennes).",
    "answers": [
      "La Défense",
      "Esplanade de la Défense",
      "Pont de Neuilly",
      "Les Sablons",
      "Porte Maillot",
      "Argentine",
      "Charles de Gaulle - Étoile",
      "George V",
      "Franklin D. Roosevelt",
      "Champs-Élysées - Clemenceau",
      "Concorde",
      "Tuileries",
      "Palais Royal - Musée du Louvre",
      "Louvre - Rivoli",
      "Châtelet",
      "Hôtel de Ville",
      "Saint-Paul",
      "Bastille",
      "Gare de Lyon",
      "Reuilly - Diderot",
      "Nation",
      "Porte de Vincennes",
      "Saint-Mandé",
      "Berault",
      "Château de Vincennes"
    ]
  },
  {
    "id": "ligne13",
    "title": "ARRÊTS LIGNE 13 DU MÉTRO",
    "icon": "../assets/Images/geographie.png",
    "question": "Citez un maximum d'arrêts de la ligne 13 du métro (Saint-Denis / Les Courtilles — Châtillon-Montrouge).",
    "answers": [
      "Saint-Denis - Université",
      "Saint-Denis - Porte de Paris",
      "Carrefour Pleyel",
      "Mairie de Saint-Ouen",
      "Garibaldi",
      "Les Courtilles",
      "Asnières - Gennevilliers - Les Courtilles",
      "Gabriel Péri",
      "Gennevilliers",
      "Les Agnettes",
      "Porte de Clichy",
      "Brochant",
      "La Fourche",
      "Place de Clichy",
      "Liège",
      "Saint-Lazare",
      "Miromesnil",
      "Champs-Élysées - Clemenceau",
      "Invalides",
      "Varenne",
      "Saint-François-Xavier",
      "Duroc",
      "Montparnasse - Bienvenüe",
      "Gaîté",
      "Pernety",
      "Plaisance",
      "Porte de Vanves",
      "Malakoff - Plateau de Vanves",
      "Malakoff - Rue Étienne Dolet",
      "Châtillon - Montrouge"
    ]
  },
  {
    "id": "ligne3",
    "title": "ARRÊTS LIGNE 3 DU MÉTRO",
    "icon": "../assets/Images/geographie.png",
    "question": "Citez un maximum d'arrêts de la ligne 3 du métro (Pont de Levallois-Bécon — Gallieni).",
    "answers": [
      "Pont de Levallois - Bécon",
      "Anatole France",
      "Louise Michel",
      "Porte de Champerret",
      "Pereire",
      "Wagram",
      "Malesherbes",
      "Villiers",
      "Europe",
      "Saint-Lazare",
      "Havre - Caumartin",
      "Opéra",
      "Quatre-Septembre",
      "Bourse",
      "Sentier",
      "Arts et Métiers",
      "Temple",
      "République",
      "Parmentier",
      "Père Lachaise",
      "Gambetta",
      "Porte de Bagnolet",
      "Gallieni"
    ]
  },
  {
    "id": "ligne4",
    "title": "ARRÊTS LIGNE 4 DU MÉTRO",
    "icon": "../assets/Images/geographie.png",
    "question": "Citez un maximum d'arrêts de la ligne 4 du métro (Montrouge — Montrouge / Clignancourt — Bagneux).",
    "answers": [
      "Montrouge",
      "Bagneux - Lucie Aubrac",
      "Barbara",
      "Porte d'Orléans",
      "Mouton-Duvernet",
      "Alésia",
      "Denfert-Rochereau",
      "Raspail",
      "Vavin",
      "Montparnasse - Bienvenüe",
      "Edgar Quinet",
      "Saint-Placide",
      "Saint-Sulpice",
      "Saint-Germain-des-Prés",
      "Odéon",
      "Cluny - La Sorbonne",
      "Saint-Michel",
      "Cité",
      "Châtelet",
      "Les Halles",
      "Étienne Marcel",
      "Réaumur - Sébastopol",
      "Strasbourg - Saint-Denis",
      "Gare du Nord",
      "Gare de l'Est",
      "Château-Landon",
      "Louis Blanc",
      "Jaurès",
      "Stalingrad",
      "Barbès - Rochechouart",
      "Château Rouge",
      "Marcadet - Poissonniers",
      "Simplon",
      "Porte de Clignancourt"
    ]
  },
  {
    "id": "ligne6",
    "title": "ARRÊTS LIGNE 6 DU MÉTRO",
    "icon": "../assets/Images/geographie.png",
    "question": "Citez un maximum d'arrêts de la ligne 6 du métro (Charles de Gaulle - Étoile — Nation).",
    "answers": [
      "Charles de Gaulle - Étoile",
      "Kléber",
      "Boissière",
      "Trocadéro",
      "Passy",
      "Bir-Hakeim",
      "Dupleix",
      "La Motte-Picquet - Grenelle",
      "Cambronne",
      "Sèvres - Lecourbe",
      "Pasteur",
      "Montparnasse - Bienvenüe",
      "Edgar Quinet",
      "Raspail",
      "Denfert-Rochereau",
      "Saint-Jacques",
      "Glacière",
      "Corvisart",
      "Place d'Italie",
      "Nationale",
      "Chevaleret",
      "Quai de la Gare",
      "Bercy",
      "Dugommier",
      "Daumesnil",
      "Bel-Air",
      "Picpus",
      "Nation"
    ]
  },
  {
    "id": "ligne8",
    "title": "ARRÊTS LIGNE 8 DU MÉTRO",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum d'arrêts de la ligne 8 du métro (Balard — Créteil-Pointe du Lac).",
    "answers": [
      "Balard",
      "Lourmel",
      "Boucicaut",
      "Félix Faure",
      "Commerce",
      "La Motte-Picquet Grenelle",
      "École Militaire",
      "La Tour-Maubourg",
      "Invalides",
      "Concorde",
      "Madeleine",
      "Opéra",
      "Richelieu-Drouot",
      "Grands Boulevards",
      "Bonne Nouvelle",
      "Strasbourg-Saint-Denis",
      "République",
      "Filles du Calvaire",
      "Saint-Sébastien Froissart",
      "Chemin Vert",
      "Bastille",
      "Ledru-Rollin",
      "Faidherbe-Chaligny",
      "Reuilly-Diderot",
      "Montgallet",
      "Daumesnil",
      "Michel Bizot",
      "Porte Dorée",
      "Porte de Charenton",
      "Liberté",
      "Charenton-Écoles",
      "École Vétérinaire",
      "Maisons-Alfort",
      "Créteil-Université",
      "Créteil-L'Échat",
      "Créteil-Préfecture",
      "Pointe du Lac"
    ]
  },
  {
    "id": "ligue1",
    "title": "CLUBS DE LIGUE 1",
    "icon": "../assets/Images/sport.png",
    "question": "Citez un maximum de clubs ayant joué en Ligue 1 depuis 2010.",
    "answers": [
      "Paris Saint-Germain",
      "PSG",
      "Olympique de Marseille",
      "OM",
      "Olympique Lyonnais",
      "OL",
      "AS Monaco",
      "RC Lens",
      "LOSC Lille",
      "OGC Nice",
      "Stade Rennais",
      "Montpellier",
      "Strasbourg",
      "Nantes",
      "Brest",
      "Toulouse",
      "Le Havre",
      "Auxerre",
      "Reims",
      "Saint-Étienne",
      "Angers",
      "Bordeaux",
      "Valenciennes",
      "Évian",
      "Ajaccio",
      "Clermont",
      "Troyes",
      "Lorient",
      "Metz",
      "Caen",
      "Guingamp"
    ]
  },
  {
    "id": "metro_lignes",
    "title": "LIGNES DU MÉTRO PARISIEN",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de lignes du métro parisien (numéros et/ou noms de terminus).",
    "answers": [
      "Ligne 1",
      "Ligne 2",
      "Ligne 3",
      "Ligne 3bis",
      "Ligne 4",
      "Ligne 5",
      "Ligne 6",
      "Ligne 7",
      "Ligne 7bis",
      "Ligne 8",
      "Ligne 9",
      "Ligne 10",
      "Ligne 11",
      "Ligne 12",
      "Ligne 13",
      "Ligne 14",
      "La Défense",
      "Château de Vincennes",
      "Nation",
      "Mairie des Lilas",
      "Porte Dauphine",
      "Bobigny",
      "Balard",
      "Créteil-Préfecture",
      "Saint-Denis-Pleyel",
      "Olympiades"
    ]
  },
  {
    "id": "parcs",
    "title": "PARCS ET JARDINS PARISIENS",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de parcs, jardins ou bois de Paris et sa petite couronne.",
    "answers": [
      "Jardin du Luxembourg",
      "Jardin des Tuileries",
      "Parc des Buttes-Chaumont",
      "Parc Monceau",
      "Parc Montsouris",
      "Champ de Mars",
      "Jardin des Plantes",
      "Parc de la Villette",
      "Parc André Citroën",
      "Bois de Boulogne",
      "Bois de Vincennes",
      "Parc de Bercy",
      "Jardin du Palais Royal",
      "Parc de Belleville",
      "Square des Batignolles",
      "Jardin d'Acclimatation",
      "Promenade Plantée",
      "Parc Kellermann",
      "Parc Georges-Brassens",
      "Jardin Tino Rossi",
      "Parc de Saint-Cloud",
      "Parc de Sceaux"
    ]
  },
  {
    "id": "plats_fr",
    "title": "PLATS FRANÇAIS TRADITIONNELS",
    "icon": "../assets/Images/cuisine.png",
    "question": "Citez un maximum de plats ou spécialités culinaires traditionnellement français.",
    "answers": [
      "Bouillabaisse",
      "Pot-au-feu",
      "Cassoulet",
      "Ratatouille",
      "Bœuf bourguignon",
      "Coq au vin",
      "Blanquette de veau",
      "Quiche lorraine",
      "Soupe à l'oignon",
      "Tartiflette",
      "Raclette",
      "Fondue savoyarde",
      "Choucroute",
      "Confit de canard",
      "Gratin dauphinois",
      "Magret de canard",
      "Foie gras",
      "Escargots de Bourgogne",
      "Sole meunière",
      "Tête de veau",
      "Cervelle de canut",
      "Crêpes bretonnes",
      "Galette complète",
      "Kouign-amann",
      "Clafoutis",
      "Tarte tatin",
      "Flamiche",
      "Garbure",
      "Pistou"
    ]
  },
  {
    "id": "presidents_fr",
    "title": "PRÉSIDENTS DE LA Ve RÉPUBLIQUE",
    "icon": "../assets/Images/histoire.png",
    "question": "Citez les présidents de la Cinquième République française avec leur nom ou prénom.",
    "answers": [
      "De Gaulle",
      "Charles de Gaulle",
      "Pompidou",
      "Georges Pompidou",
      "Giscard d'Estaing",
      "Valéry Giscard d'Estaing",
      "Mitterrand",
      "François Mitterrand",
      "Chirac",
      "Jacques Chirac",
      "Sarkozy",
      "Nicolas Sarkozy",
      "Hollande",
      "François Hollande",
      "Macron",
      "Emmanuel Macron"
    ]
  },
  {
    "id": "series_fr",
    "title": "SÉRIES FRANÇAISES",
    "icon": "../assets/Images/cinema.png",
    "question": "Citez un maximum de séries françaises (tous supports : TV, streaming, etc.).",
    "answers": [
      "Lupin",
      "Kaamelott",
      "Engrenages",
      "Dix pour cent",
      "Braquo",
      "Call My Agent",
      "Plus belle la vie",
      "Marseille",
      "Au Service de la France",
      "Plan Cœur",
      "Bref",
      "Validé",
      "La Flamme",
      "Versailles",
      "Baron Noir",
      "Capitaine Marleau",
      "Section de recherches",
      "Profilage",
      "Laetitia",
      "Mortel",
      "Family Business",
      "Nox",
      "Skam France",
      "Ainsi soient-ils",
      "Les Revenants",
      "Un village français"
    ]
  },
  {
    "id": "ue",
    "title": "PAYS DE L'UNION EUROPÉENNE",
    "icon": "../assets/Images/histoire.png",
    "question": "Citez un maximum de pays membres de l'Union Européenne (27 membres).",
    "answers": [
      "Allemagne",
      "Autriche",
      "Belgique",
      "Bulgarie",
      "Chypre",
      "Croatie",
      "Danemark",
      "Espagne",
      "Estonie",
      "Finlande",
      "France",
      "Grèce",
      "Hongrie",
      "Irlande",
      "Italie",
      "Lettonie",
      "Lituanie",
      "Luxembourg",
      "Malte",
      "Pays-Bas",
      "Pologne",
      "Portugal",
      "Roumanie",
      "Slovaquie",
      "Slovénie",
      "Suède",
      "Tchéquie"
    ]
  }
];
