const THEMES_DATA = [
  {
    "id": "afrique",
    "title": "PAYS D'AFRIQUE",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de pays du continent africain.",
    "answers": [
      "Afrique du Sud",
      "Algérie",
      "Angola",
      "Bénin",
      "Botswana",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cameroun",
      "République centrafricaine",
      "Comores",
      "République du Congo",
      "République démocratique du Congo",
      "Côte d’Ivoire",
      "Djibouti",
      "Égypte",
      "Érythrée",
      "Eswatini",
      "Éthiopie",
      "Gabon",
      "Gambie",
      "Ghana",
      "Guinée",
      "Guinée-Bissau",
      "Guinée équatoriale",
      "Kenya",
      "Lesotho",
      "Liberia",
      "Libye",
      "Madagascar",
      "Malawi",
      "Mali",
      "Maroc",
      "Maurice",
      "Mauritanie",
      "Mozambique",
      "Namibie",
      "Niger",
      "Nigeria",
      "Ouganda",
      "Rwanda",
      "Sao Tomé-et-Principe",
      "Sénégal",
      "Seychelles",
      "Sierra Leone",
      "Somalie",
      "Soudan",
      "Soudan du Sud",
      "Tanzanie",
      "Tchad",
      "Togo",
      "Tunisie",
      "Zambie",
      "Zimbabwe"
    ]
  },
  {
    "id": "amerique_latine",
    "title": "PAYS D'AMÉRIQUE LATINE",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de pays d'Amérique latine.",
    "answers": [
      "Argentine",
      "Bolivie",
      "Brésil",
      "Chili",
      "Colombie",
      "Costa Rica",
      "Cuba",
      "République dominicaine",
      "Équateur",
      "Salvador",
      "Guatemala",
      "Haïti",
      "Honduras",
      "Mexique",
      "Nicaragua",
      "Panama",
      "Paraguay",
      "Pérou",
      "Uruguay",
      "Venezuela"
    ]
  },
  {
    "id": "animaux_fr",
    "title": "ANIMAUX DE LA FERME",
    "icon": "../assets/Images/animaux.png",
    "question": "Citez un maximum d'animaux qu'on trouve traditionnellement dans une ferme.",
    "answers": [
      "Vache",
      "Cochon",
      "Mouton",
      "Chèvre",
      "Poulet",
      "Poule",
      "Coq",
      "Canard",
      "Oie",
      "Dinde",
      "Lapin",
      "Cheval",
      "Âne",
      "Mule",
      "Bœuf",
      "Taureau",
      "Veau",
      "Agneau",
      "Cabri",
      "Chien",
      "Chat",
      "Pigeon",
      "Pintade",
      "Caille",
      "Faisan",
      "Abeille",
      "Ver à soie",
      "Porc",
      "Truie",
      "Poney"
    ]
  },
  {
    "id": "arrets_ligne_metro_10",
    "title": "ARRÊTS LIGNE 10 DU MÉTRO",
    "icon": "assets/Images/geographie.png",
    "question": "ARRÊTS LIGNE 10 DU MÉTRO",
    "answers": [
      "Boulogne – Pont de Saint-Cloud",
      "Boulogne – Jean Jaurès",
      "Porte d’Auteuil",
      "Michel-Ange – Molitor",
      "Michel-Ange – Auteuil",
      "Chardon-Lagache",
      "Église d’Auteuil",
      "Javel – André Citroën",
      "Charles Michels",
      "Avenue Émile Zola",
      "La Motte-Picquet – Grenelle",
      "Ségur",
      "Duroc",
      "Vaneau",
      "Sèvres – Babylone",
      "Mabillon",
      "Odéon",
      "Cluny – La Sorbonne",
      "Maubert – Mutualité",
      "Cardinal Lemoine",
      "Jussieu",
      "Gare d’Austerlitz",
      "Mrabeau"
    ]
  },
  {
    "id": "arrets_metro_ligne_5",
    "title": "ARRÊTS LIGNE 5 DU MÉTRO",
    "icon": "assets/Images/geographie.png",
    "question": "ARRÊTS LIGNE 5 DU MÉTRO",
    "answers": [
      "Place d'Italie",
      "Campo-Formio",
      "Saint-Marcel",
      "Gare d'Austerlitz",
      "Quai de la Rapée",
      "Bastille",
      "Bréguet-Sabin",
      "Richard-Lenoir",
      "Oberkampf",
      "République",
      "Jacques Bonsergent",
      "Gare de l'Est",
      "Gare du Nord",
      "Stalingrad",
      "Jaurès",
      "Laumière",
      "Ourcq",
      "Porte de Pantin",
      "Hiche",
      "Eglise de Pantin",
      "Bobigny-Pantin Raymon Q.",
      "Bobigny-Pablo Picasso"
    ]
  },
  {
    "id": "arrets_metro_ligne_7",
    "title": "ARRÊTS LIGNE 7 DU MÉTRO",
    "icon": "assets/Images/geographie.png",
    "question": "ARRÊTS LIGNE 7 DU MÉTRO",
    "answers": [
      "La Courneuve – 8 Mai 1945",
      "Fort d’Aubervilliers",
      "Aubervilliers – Pantin – Quatre Chemins",
      "Porte de la Villette",
      "Corentin Cariou",
      "Crimée",
      "Riquet",
      "Stalingrad",
      "Louis Blanc",
      "Château-Landon",
      "Gare de l’Est",
      "Poissonnière",
      "Cadet",
      "Le Peletier",
      "Chaussée d’Antin – La Fayette",
      "Opéra",
      "Pyramides",
      "Palais Royal – Musée du Louvre",
      "Pont Neuf",
      "Châtelet",
      "Pont Marie",
      "Sully – Morland",
      "Jussieu",
      "Place Monge",
      "Censier – Daubenton",
      "Les Gobelins",
      "Place d’Italie",
      "Tolbiac",
      "Maison Blanche",
      "Le Kremlin-Bicêtre",
      "Villejuif – Léo Lagrange",
      "Villejuif – Paul Vaillant-Couturier",
      "Villejuif – Louis Aragon",
      "Porte d’Italie",
      "Porte de Choisy",
      "Porte d’Ivry",
      "Pierre et Marie Curie",
      "Mairie d’Ivry"
    ]
  },
  {
    "id": "arrets_metro_ligne_9",
    "title": "ARRÊTS LIGNE 9 DU MÉTRO",
    "icon": "assets/Images/geographie.png",
    "question": "ARRÊTS LIGNE 9 DU MÉTRO",
    "answers": [
      "Pont de Sèvres",
      "Billancourt",
      "Marcel Sembat",
      "Porte de Saint-Cloud",
      "Exelmans",
      "Michel-Ange – Molitor",
      "Michel-Ange – Auteuil",
      "Jasmin",
      "Ranelagh",
      "La Muette",
      "Rue de la Pompe",
      "Trocadéro",
      "Iéna",
      "Alma – Marceau",
      "Franklin D. Roosevelt",
      "Saint-Philippe du Roule",
      "Miromesnil",
      "Saint-Augustin",
      "Havre – Caumartin",
      "Chaussée d’Antin – La Fayette",
      "Richelieu – Drouot",
      "Grands Boulevards",
      "Bonne Nouvelle",
      "Strasbourg – Saint-Denis",
      "République",
      "Oberkampf",
      "Saint-Ambroise",
      "Voltaire",
      "Charonne",
      "Rue des Boulets",
      "Nation",
      "Buzenval",
      "Maraîchers",
      "Porte de Montreuil",
      "Robespierre",
      "Croix de Chavaux",
      "Mairie de Montreuil"
    ]
  },
  {
    "id": "artistes_fr",
    "title": "CHANTEURS FRANÇAIS",
    "icon": "../assets/Images/musique.png",
    "question": "Citez un maximum d'artistes ou chanteurs français (solo ou groupe).",
    "answers": [
      "Édith Piaf",
      "Charles Aznavour",
      "Jacques Brel",
      "Georges Brassens",
      "Serge Gainsbourg",
      "Barbara",
      "Juliette Gréco",
      "Gilbert Bécaud",
      "Yves Montand",
      "Joe Dassin",
      "Johnny Hallyday",
      "Michel Sardou",
      "Francis Cabrel",
      "Jean-Jacques Goldman",
      "Patrick Bruel",
      "Véronique Sanson",
      "Mylène Farmer",
      "Florent Pagny",
      "Patricia Kaas",
      "Céline Dion",
      "Calogero",
      "Zazie",
      "Christophe Maé",
      "Amir",
      "Clara Luciani",
      "Vianney",
      "Louane",
      "Zaz",
      "IAM",
      "NTM",
      "MC Solaar",
      "Booba",
      "Jul",
      "Orelsan",
      "SCH",
      "Ninho",
      "Damso",
      "PNL",
      "Aya Nakamura",
      "Angèle",
      "Pierre de Maere",
      "Slimane",
      "Vitaa",
      "Dadju",
      "Tayc",
      "Gims",
      "Kendji Girac",
      "Soprano"
    ]
  },
  {
    "id": "capitales_eu",
    "title": "CAPITALES EUROPÉENNES",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de capitales de pays européens.",
    "answers": [
      "Tirana",
      "Berlin",
      "Andorre-la-Vieille",
      "Vienne",
      "Bruxelles",
      "Minsk",
      "Sarajevo",
      "Sofia",
      "Nicosie",
      "Zagreb",
      "Copenhague",
      "Madrid",
      "Tallinn",
      "Helsinki",
      "Paris",
      "Athènes",
      "Budapest",
      "Dublin",
      "Reykjavik",
      "Rome",
      "Pristina",
      "Riga",
      "Vaduz",
      "Vilnius",
      "Luxembourg",
      "Skopje",
      "La Valette",
      "Chișinău",
      "Monaco",
      "Podgorica",
      "Oslo",
      "Amsterdam",
      "Varsovie",
      "Lisbonne",
      "Prague",
      "Bucarest",
      "Londres",
      "Moscou",
      "Saint-Marin",
      "Belgrade",
      "Bratislava",
      "Ljubljana",
      "Stockholm",
      "Berne",
      "Kyiv",
      "Vatican"
    ]
  },
  {
    "id": "ciup",
    "title": "MAISONS DE LA CIUP",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de maisons de la Cité Internationale Universitaire de Paris.",
    "answers": [
      "Fondation Rosa Abreu de Grancher",
      "Résidence André Honnorat",
      "Maison de l’Argentine",
      "Maison des étudiants arméniens",
      "Maison des Arts et Métiers",
      "Maison de l’Asie du Sud-Est",
      "Fondation Avicenne / L’Oblique",
      "Fondation Biermans-Lapôtre",
      "Maison du Brésil",
      "Maison du Cambodge",
      "Maison des étudiants canadiens",
      "Fondation danoise",
      "Fondation Deutsch de la Meurthe",
      "Collège d’Espagne",
      "Fondation des États-Unis",
      "Collège franco-britannique",
      "Fondation hellénique",
      "Maison Heinrich Heine",
      "Maison de l’Inde",
      "Maison de l’Italie",
      "Maison du Japon",
      "Maison du Liban",
      "Résidence Lila",
      "Résidence Lucien Paye",
      "Maison du Maroc",
      "Maison du Mexique",
      "Fondation de Monaco",
      "Collège néerlandais",
      "Maison de Norvège",
      "Maison des Provinces de France",
      "Résidence Quai de la Loire",
      "Résidence Robert Garric",
      "Maison de la Suède",
      "Pavillon suisse",
      "Maison de la Tunisie",
      "Fondation Victor Lyon",
      "Maison de la Corée",
      "Maison de l’Égypte",
      "Maison de l’Île-de-France",
      "Maison de l’Ukraine",
      "Maison internationale AgroParisTech",
      "Maison des étudiants de la francophonie"
    ]
  },
  {
    "id": "departements",
    "title": "DÉPARTEMENTS FRANÇAIS",
    "icon": "../assets/Images/histoire.png",
    "question": "Citez un maximum de départements français (par leur nom).",
    "answers": [
      "Ain",
      "Aisne",
      "Allier",
      "Alpes-de-Haute-Provence",
      "Hautes-Alpes",
      "Alpes-Maritimes",
      "Ardèche",
      "Ardennes",
      "Ariège",
      "Aube",
      "Aude",
      "Aveyron",
      "Bouches-du-Rhône",
      "Calvados",
      "Cantal",
      "Charente",
      "Charente-Maritime",
      "Cher",
      "Corrèze",
      "Corse-du-Sud",
      "Haute-Corse",
      "Côte-d'Or",
      "Côtes-d'Armor",
      "Creuse",
      "Dordogne",
      "Doubs",
      "Drôme",
      "Eure",
      "Eure-et-Loir",
      "Finistère",
      "Gard",
      "Haute-Garonne",
      "Gers",
      "Gironde",
      "Hérault",
      "Ille-et-Vilaine",
      "Indre",
      "Indre-et-Loire",
      "Isère",
      "Jura",
      "Landes",
      "Loir-et-Cher",
      "Loire",
      "Haute-Loire",
      "Loire-Atlantique",
      "Loiret",
      "Lot",
      "Lot-et-Garonne",
      "Lozère",
      "Maine-et-Loire",
      "Manche",
      "Marne",
      "Haute-Marne",
      "Mayenne",
      "Meurthe-et-Moselle",
      "Meuse",
      "Morbihan",
      "Moselle",
      "Nièvre",
      "Nord",
      "Oise",
      "Orne",
      "Pas-de-Calais",
      "Puy-de-Dôme",
      "Pyrénées-Atlantiques",
      "Hautes-Pyrénées",
      "Pyrénées-Orientales",
      "Bas-Rhin",
      "Haut-Rhin",
      "Rhône",
      "Haute-Saône",
      "Saône-et-Loire",
      "Sarthe",
      "Savoie",
      "Haute-Savoie",
      "Paris",
      "Seine-Maritime",
      "Seine-et-Marne",
      "Yvelines",
      "Deux-Sèvres",
      "Somme",
      "Tarn",
      "Tarn-et-Garonne",
      "Var",
      "Vaucluse",
      "Vendée",
      "Vienne",
      "Haute-Vienne",
      "Vosges",
      "Yonne",
      "Territoire de Belfort",
      "Essonne",
      "Hauts-de-Seine",
      "Seine-Saint-Denis",
      "Val-de-Marne",
      "Val-d'Oise",
      "Guadeloupe",
      "Martinique",
      "Guyane",
      "La Réunion",
      "Mayotte"
    ]
  },
  {
    "id": "europe",
    "title": "PAYS D'EUROPE",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de pays du continent européen.",
    "answers": [
      "Albanie",
      "Allemagne",
      "Andorre",
      "Autriche",
      "Belgique",
      "Biélorussie",
      "Bosnie-Herzégovine",
      "Bulgarie",
      "Chypre",
      "Croatie",
      "Danemark",
      "Espagne",
      "Estonie",
      "Finlande",
      "France",
      "Grèce",
      "Hongrie",
      "Irlande",
      "Islande",
      "Italie",
      "Kosovo",
      "Lettonie",
      "Liechtenstein",
      "Lituanie",
      "Luxembourg",
      "Macédoine du Nord",
      "Malte",
      "Moldavie",
      "Monaco",
      "Monténégro",
      "Norvège",
      "Pays-Bas",
      "Pologne",
      "Portugal",
      "République tchèque",
      "Roumanie",
      "Royaume-Uni",
      "Russie",
      "Saint-Marin",
      "Serbie",
      "Slovaquie",
      "Slovénie",
      "Suède",
      "Suisse",
      "Ukraine",
      "Vatican"
    ]
  },
  {
    "id": "films_fr",
    "title": "FILMS FRANÇAIS CULTES",
    "icon": "../assets/Images/cinema.png",
    "question": "Citez un maximum de films français devenus cultes ou iconiques.",
    "answers": [
      "Intouchables",
      "Le Fabuleux Destin d'Amélie Poulain",
      "La Haine",
      "Les Visiteurs",
      "Bienvenue chez les Ch'tis",
      "Léon",
      "Les Choristes",
      "Un Prophète",
      "Le Dîner de Cons",
      "À Bout de Souffle",
      "OSS 117",
      "Nikita",
      "Taxi",
      "La Cité de la Peur",
      "La Grande Vadrouille",
      "Astérix Mission Cléopâtre",
      "Le Grand Bleu",
      "La Vie en Rose",
      "8 Femmes",
      "Trois Hommes et un Couffin",
      "Les Misérables",
      "Au Revoir les Enfants",
      "Le Fabuleux",
      "Banlieue 13",
      "La Vérité si je mens",
      "Qu'est-ce qu'on a fait au Bon Dieu",
      "Le Grand Bain",
      "Les Bronzés",
      "Les Bronzés font du ski",
      "Le Père Noël est une ordure",
      "Rabbi Jacob",
      "Astérix et Obélix : Mission Cléopâtre",
      "Le Samouraï",
      "Les Enfants du paradis",
      "Le Pacte des loups",
      "36 Quai des Orfèvres",
      "Le Salaire de la peur",
      "Le Cercle rouge",
      "Le Prénom",
      "Camping",
      "Neuilly sa mère !",
      "Kirikou et la Sorcière",
      "Persepolis",
      "Le Roi et l'Oiseau",
      "Arthur et les Minimoys",
      "Jules et Jim",
      "Les 400 Coups",
      "Pierrot le Fou"
    ]
  },
  {
    "id": "fleuves",
    "title": "FLEUVES",
    "icon": "assets/Images/geographie.png",
    "question": "FLEUVES",
    "answers": [
      "Seine",
      "Loire",
      "Rhin",
      "Danube",
      "Volga",
      "Tamise",
      "Nil",
      "Congo",
      "Niger",
      "Zambèze",
      "Amazone",
      "Mississippi",
      "Saint-Laurent",
      "Paraná",
      "Yangtsé",
      "Gange",
      "Mékong",
      "Indus",
      "Tigre",
      "Euphrate",
      "Murray"
    ]
  },
  {
    "id": "g20",
    "title": "PAYS DU G20",
    "icon": "../assets/Images/histoire.png",
    "question": "Citez un maximum de pays membres du G20.",
    "answers": [
      "Afrique du Sud",
      "Allemagne",
      "Arabie Saoudite",
      "Argentine",
      "Australie",
      "Brésil",
      "Canada",
      "Chine",
      "Corée du Sud",
      "États-Unis",
      "France",
      "Inde",
      "Indonésie",
      "Italie",
      "Japon",
      "Mexique",
      "Royaume-Uni",
      "Russie",
      "Turquie",
      "Union Européenne",
      "Union africaine"
    ]
  },
  {
    "id": "gagnants_le_ballon_d_or",
    "title": "GAGNATS BALLONS D'OR (Football)",
    "icon": "assets/Images/geographie.png",
    "question": "GAGNATS BALLONS D'OR (Football)",
    "answers": [
      "Stanley Matthews",
      "Alfredo Di Stéfano",
      "Raymond Kopa",
      "Luis Suárez",
      "Omar Sívori",
      "Josef Masopust",
      "Lev Yachine",
      "Denis Law",
      "Eusébio",
      "Bobby Charlton",
      "Flórián Albert",
      "George Best",
      "Gianni Rivera",
      "Gerd Müller",
      "Johan Cruyff",
      "Franz Beckenbauer",
      "Allan Simonsen",
      "Kevin Keegan",
      "Karl-Heinz Rummenigge",
      "Paolo Rossi",
      "Michel Platini",
      "Igor Belanov",
      "Ruud Gullit",
      "Marco van Basten",
      "Lothar Matthäus",
      "Jean-Pierre Papin",
      "Roberto Baggio",
      "Hristo Stoichkov",
      "George Weah",
      "Matthias Sammer",
      "Ronaldo",
      "Zinedine Zidane",
      "Rivaldo",
      "Luis Figo",
      "Michael Owen",
      "Pavel Nedvěd",
      "Andriy Shevchenko",
      "Ronaldinho",
      "Fabio Cannavaro",
      "Kaká",
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Luka Modrić",
      "Karim Benzema",
      "Ousmane Dembélé"
    ]
  },
  {
    "id": "grandes_villes_fr",
    "title": "GRANDES VILLES FRANÇAISES",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de grandes villes françaises.",
    "answers": [
      "Paris",
      "Marseille",
      "Lyon",
      "Toulouse",
      "Nice",
      "Nantes",
      "Montpellier",
      "Strasbourg",
      "Bordeaux",
      "Lille",
      "Rennes",
      "Reims",
      "Le Havre",
      "Saint-Étienne",
      "Toulon",
      "Grenoble",
      "Dijon",
      "Angers",
      "Nîmes",
      "Villeurbanne",
      "Saint-Denis",
      "Clermont-Ferrand",
      "Le Mans",
      "Aix-en-Provence",
      "Brest",
      "Tours",
      "Limoges",
      "Amiens",
      "Metz",
      "Besançon"
    ]
  },
  {
    "id": "instruments",
    "title": "INSTRUMENTS DE MUSIQUE",
    "icon": "../assets/Images/musique.png",
    "question": "Citez un maximum d'instruments de musique (tous genres confondus).",
    "answers": [
      "Violon",
      "Alto",
      "Violoncelle",
      "Contrebasse",
      "Guitare",
      "Guitare électrique",
      "Basse électrique",
      "Harpe",
      "Ukulélé",
      "Mandoline",
      "Banjo",
      "Luth",
      "Flûte traversière",
      "Clarinette",
      "Hautbois",
      "Basson",
      "Saxophone",
      "Flûte à bec",
      "Trompette",
      "Trombone",
      "Tuba",
      "Cor",
      "Bugle",
      "Batterie",
      "Tambour",
      "Djembé",
      "Conga",
      "Bongo",
      "Xylophone",
      "Marimba",
      "Triangle",
      "Cymbales",
      "Castagnettes",
      "Piano",
      "Orgue",
      "Clavecin",
      "Accordéon",
      "Synthétiseur",
      "Boîte à rythmes",
      "Theremin",
      "Sampler",
      "MPC",
      "Sitar",
      "Kora",
      "Balalaïka",
      "Didgeridoo",
      "Shamisen",
      "Oud",
      "Bouzouki",
      "Kalimba"
    ]
  },
  {
    "id": "jo_sports",
    "title": "SPORTS AUX JO D'ÉTÉ",
    "icon": "../assets/Images/sport.png",
    "question": "Citez un maximum de disciplines présentes aux Jeux Olympiques d'été.",
    "answers": [
      "Athlétisme",
      "Natation",
      "Cyclisme",
      "Judo",
      "Tennis",
      "Football",
      "Basketball",
      "Volleyball",
      "Rugby à 7",
      "Boxe",
      "Lutte",
      "Escrime",
      "Tir",
      "Aviron",
      "Kayak",
      "Canoë",
      "Voile",
      "Équitation",
      "Haltérophilie",
      "Tir à l'arc",
      "Pentathlon moderne",
      "Badminton",
      "Tennis de table",
      "Handball",
      "Water-polo",
      "Plongeon",
      "Natation synchronisée",
      "Trampoline",
      "Golf",
      "Surf",
      "Skateboard",
      "Escalade",
      "Breaking",
      "Taekwondo",
      "Triathlon",
      "Courses (100 m, marathon, relais…)",
      "Sauts (longueur, hauteur, perche…)",
      "Lancers (poids, javelot, disque…)",
      "Natation synchronisée (artistique)",
      "Tir à l’arc",
      "Canoë-kayak",
      "Escalade sportive"
    ]
  },
  {
    "id": "langues",
    "title": "LANGUES LES PLUS PARLÉES",
    "icon": "../assets/Images/histoire.png",
    "question": "Citez un maximum de langues parmi les 30 plus parlées au monde.",
    "answers": [
      "Mandarin",
      "Espagnol",
      "Anglais",
      "Hindi",
      "Arabe",
      "Bengali",
      "Portugais",
      "Russe",
      "Japonais",
      "Punjabi",
      "Malais",
      "Télougou",
      "Marathi",
      "Tamoul",
      "Français",
      "Allemand",
      "Ourdou",
      "Persan",
      "Swahili",
      "Turc",
      "Coréen",
      "Vietnamien",
      "Italien",
      "Polonais",
      "Ukrainien",
      "Néerlandais",
      "Indonésien",
      "Thaï",
      "Birman",
      "Gujarati"
    ]
  },
  {
    "id": "ligne1",
    "title": "ARRÊTS LIGNE 1 DU MÉTRO",
    "icon": "../assets/Images/geographie.png",
    "question": "Citez un maximum d'arrêts de la ligne 1 du métro ",
    "answers": [
      "La Défense",
      "Esplanade de la Défense",
      "Pont de Neuilly",
      "Les Sablons",
      "Porte Maillot",
      "Argentine",
      "Charles de Gaulle - Étoile",
      "George V",
      "Franklin D. Roosevelt",
      "Champs-Élysées - Clemenceau",
      "Concorde",
      "Tuileries",
      "Palais Royal - Musée du Louvre",
      "Louvre - Rivoli",
      "Châtelet",
      "Hôtel de Ville",
      "Saint-Paul",
      "Bastille",
      "Gare de Lyon",
      "Reuilly - Diderot",
      "Nation",
      "Porte de Vincennes",
      "Saint-Mandé",
      "Berault",
      "Château de Vincennes"
    ]
  },
  {
    "id": "ligne13",
    "title": "ARRÊTS LIGNE 13 DU MÉTRO",
    "icon": "../assets/Images/geographie.png",
    "question": "Citez un maximum d'arrêts de la ligne 13 du métro.",
    "answers": [
      "Saint-Denis - Université",
      "Saint-Denis - Porte de Paris",
      "Carrefour Pleyel",
      "Mairie de Saint-Ouen",
      "Garibaldi",
      "Les Courtilles",
      "Asnières - Gennevilliers - Les Courtilles",
      "Gabriel Péri",
      "Gennevilliers",
      "Les Agnettes",
      "Porte de Clichy",
      "Brochant",
      "La Fourche",
      "Place de Clichy",
      "Liège",
      "Saint-Lazare",
      "Miromesnil",
      "Champs-Élysées - Clemenceau",
      "Invalides",
      "Varenne",
      "Saint-François-Xavier",
      "Duroc",
      "Montparnasse - Bienvenüe",
      "Gaîté",
      "Pernety",
      "Plaisance",
      "Porte de Vanves",
      "Malakoff - Plateau de Vanves",
      "Malakoff - Rue Étienne Dolet",
      "Châtillon - Montrouge",
      "Basilique de Saint-Denis",
      "Porte de Saint-Ouen",
      "Guy Môquet",
      "Mairie de Clichy",
      "St-Denis - Université",
      "Basilique de St-Denis",
      "Mairie de St-Ouen",
      "Porte de St-Ouen"
    ]
  },
  {
    "id": "ligne3",
    "title": "ARRÊTS LIGNE 3 DU MÉTRO",
    "icon": "../assets/Images/geographie.png",
    "question": "Citez un maximum d'arrêts de la ligne 3 du métro.",
    "answers": [
      "Pont de Levallois - Bécon",
      "Anatole France",
      "Louise Michel",
      "Porte de Champerret",
      "Pereire",
      "Wagram",
      "Malesherbes",
      "Villiers",
      "Europe",
      "Saint-Lazare",
      "Havre - Caumartin",
      "Opéra",
      "Quatre-Septembre",
      "Bourse",
      "Sentier",
      "Arts et Métiers",
      "Temple",
      "République",
      "Parmentier",
      "Père Lachaise",
      "Gambetta",
      "Porte de Bagnolet",
      "Gallieni"
    ]
  },
  {
    "id": "ligne4",
    "title": "ARRÊTS LIGNE 4 DU MÉTRO",
    "icon": "../assets/Images/geographie.png",
    "question": "Citez un maximum d'arrêts de la ligne 4 du métro",
    "answers": [
      "Bagneux - Lucie Aubrac",
      "Barbara",
      "Porte d'Orléans",
      "Mouton-Duvernet",
      "Alésia",
      "Denfert-Rochereau",
      "Raspail",
      "Vavin",
      "Montparnasse - Bienvenüe",
      "Saint-Placide",
      "Saint-Sulpice",
      "Saint-Germain-des-Prés",
      "Odéon",
      "Saint-Michel",
      "Cité",
      "Châtelet",
      "Les Halles",
      "Étienne Marcel",
      "Réaumur - Sébastopol",
      "Strasbourg - Saint-Denis",
      "Gare du Nord",
      "Gare de l'Est",
      "Barbès - Rochechouart",
      "Château Rouge",
      "Marcadet - Poissonniers",
      "Simplon",
      "Porte de Clignancourt",
      "Château d'eau",
      "Mairie de Montrouge"
    ]
  },
  {
    "id": "ligne6",
    "title": "ARRÊTS LIGNE 6 DU MÉTRO",
    "icon": "../assets/Images/geographie.png",
    "question": "Citez un maximum d'arrêts de la ligne 6 du métro.",
    "answers": [
      "Charles de Gaulle - Étoile",
      "Kléber",
      "Boissière",
      "Trocadéro",
      "Passy",
      "Bir-Hakeim",
      "Dupleix",
      "La Motte-Picquet - Grenelle",
      "Cambronne",
      "Sèvres - Lecourbe",
      "Pasteur",
      "Montparnasse - Bienvenüe",
      "Edgar Quinet",
      "Raspail",
      "Denfert-Rochereau",
      "Saint-Jacques",
      "Glacière",
      "Corvisart",
      "Place d'Italie",
      "Nationale",
      "Chevaleret",
      "Quai de la Gare",
      "Bercy",
      "Dugommier",
      "Daumesnil",
      "Bel-Air",
      "Picpus",
      "Nation"
    ]
  },
  {
    "id": "ligne8",
    "title": "ARRÊTS LIGNE 8 DU MÉTRO",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum d'arrêts de la ligne 8 du métro ",
    "answers": [
      "Balard",
      "Lourmel",
      "Boucicaut",
      "Félix Faure",
      "Commerce",
      "La Motte-Picquet Grenelle",
      "École Militaire",
      "La Tour-Maubourg",
      "Invalides",
      "Concorde",
      "Madeleine",
      "Opéra",
      "Richelieu-Drouot",
      "Grands Boulevards",
      "Bonne Nouvelle",
      "Strasbourg-Saint-Denis",
      "République",
      "Filles du Calvaire",
      "Saint-Sébastien Froissart",
      "Chemin Vert",
      "Bastille",
      "Ledru-Rollin",
      "Faidherbe-Chaligny",
      "Reuilly-Diderot",
      "Montgallet",
      "Daumesnil",
      "Michel Bizot",
      "Porte Dorée",
      "Porte de Charenton",
      "Liberté",
      "Charenton-Écoles",
      "École Vétérinaire",
      "Maisons-Alfort",
      "Créteil-Université",
      "Créteil-L'Échat",
      "Créteil-Préfecture",
      "Pointe du Lac"
    ]
  },
  {
    "id": "ligne_2_du_metro",
    "title": "ARRÊTS LIGNE 2 DU MÉTRO",
    "icon": "assets/Images/geographie.png",
    "question": "ARRÊTS LIGNE 2 DU MÉTRO",
    "answers": [
      "Nation",
      "Avron",
      "Alexandre Dumas",
      "Philippe Auguste",
      "Père Lachaise",
      "Ménilmontant",
      "Couronnes",
      "Belleville",
      "Colonel Fabien",
      "Jaurès",
      "Stalingrad",
      "La chapelle",
      "Barbès-Rochechouart",
      "Anvers",
      "Pigalle",
      "Blanche",
      "Place de Clichy",
      "Rome",
      "Villiers",
      "Monceau",
      "Courcelles",
      "Ternes",
      "Charles de Gaulle Etoile",
      "Victor Hugo",
      "Porte Dauphine"
    ]
  },
  {
    "id": "ligue1",
    "title": "CLUBS DE LIGUE 1 (championnat français)",
    "icon": "../assets/Images/sport.png",
    "question": "Citez un maximum de clubs ayant joué en Ligue 1",
    "answers": [
      "Paris Saint-Germain",
      "Olympique de Marseille",
      "AS Monaco",
      "Olympique Lyonnais",
      "LOSC Lille",
      "OGC Nice",
      "RC Lens",
      "Stade Rennais FC",
      "Stade Brestois 29",
      "Toulouse FC",
      "RC Strasbourg Alsace",
      "FC Nantes",
      "Montpellier HSC",
      "AJ Auxerre",
      "Le Havre AC",
      "Angers SCO",
      "FC Metz",
      "AS Saint-Étienne"
    ]
  },
  {
    "id": "parcs",
    "title": "PARCS ET JARDINS PARISIENS",
    "icon": "../assets/Images/géographie.png",
    "question": "Citez un maximum de parcs, jardins ou bois de Paris et sa petite couronne.",
    "answers": [
      "Jardin du Luxembourg",
      "Jardin des Tuileries",
      "Parc des Buttes-Chaumont",
      "Parc Monceau",
      "Parc Montsouris",
      "Champ de Mars",
      "Jardin des Plantes",
      "Parc de la Villette",
      "Parc André Citroën",
      "Bois de Boulogne",
      "Bois de Vincennes",
      "Parc de Bercy",
      "Jardin du Palais Royal",
      "Parc de Belleville",
      "Square des Batignolles",
      "Jardin d'Acclimatation",
      "Promenade Plantée",
      "Parc Kellermann",
      "Parc Georges-Brassens",
      "Jardin Tino Rossi",
      "Parc de Saint-Cloud",
      "Parc de Sceaux",
      "Coulée verte René-Dumont",
      "Square du Vert-Galant",
      "Square des Arènes de Lutèce",
      "Parc Floral de Paris",
      "Jardin alpin du Jardin des Plantes",
      "Jardin d’agronomie tropicale René-Dumont",
      "Place des Vosges",
      "Jardin du Palais-Royal",
      "Champ-de-Mars",
      "Jardins du Trocadéro",
      "Jardin Catherine-Labouré",
      "Jardin des Serres d'Auteuil",
      "Jardin Atlantique",
      "Parc André-Citroën",
      "Parc Martin-Luther-King"
    ]
  },
  {
    "id": "plats_fr",
    "title": "PLATS FRANÇAIS TRADITIONNELS",
    "icon": "../assets/Images/cuisine.png",
    "question": "Citez un maximum de plats ou spécialités culinaires traditionnellement français.",
    "answers": [
      "Bouillabaisse",
      "Pot-au-feu",
      "Cassoulet",
      "Ratatouille",
      "Bœuf bourguignon",
      "Coq au vin",
      "Blanquette de veau",
      "Quiche lorraine",
      "Soupe à l'oignon",
      "Tartiflette",
      "Raclette",
      "Fondue savoyarde",
      "Choucroute",
      "Confit de canard",
      "Gratin dauphinois",
      "Magret de canard",
      "Foie gras",
      "Escargots de Bourgogne",
      "Sole meunière",
      "Tête de veau",
      "Cervelle de canut",
      "Crêpes bretonnes",
      "Galette complète",
      "Kouign-amann",
      "Clafoutis",
      "Tarte tatin",
      "Flamiche",
      "Garbure",
      "Pistou",
      "Choucroute garnie",
      "Soupe à l’oignon",
      "Croque-monsieur",
      "Salade niçoise",
      "Crêpes",
      "Soufflé au fromage",
      "Coquilles Saint-Jacques"
    ]
  },
  {
    "id": "presidents_fr",
    "title": "PRÉSIDENTS DE LA Ve RÉPUBLIQUE",
    "icon": "../assets/Images/histoire.png",
    "question": "Citez les présidents de la Cinquième République française",
    "answers": [
      "Charles de Gaulle (1959–1969)",
      "Georges Pompidou (1969–1974)",
      "Valéry Giscard d’Estaing (1974–1981)",
      "François Mitterrand (1981–1995)",
      "Jacques Chirac (1995–2007)",
      "Nicolas Sarkozy (2007–2012)",
      "François Hollande (2012–2017)",
      "Emmanuel Macron (2017–présent)"
    ]
  },
  {
    "id": "series_fr",
    "title": "SÉRIES FRANÇAISES",
    "icon": "../assets/Images/cinema.png",
    "question": "Citez un maximum de séries françaises.",
    "answers": [
      "Lupin",
      "Kaamelott",
      "Engrenages",
      "Dix pour cent",
      "Braquo",
      "Call My Agent",
      "Plus belle la vie",
      "Marseille",
      "Au Service de la France",
      "Plan Cœur",
      "Bref",
      "Validé",
      "La Flamme",
      "Versailles",
      "Baron Noir",
      "Capitaine Marleau",
      "Section de recherches",
      "Profilage",
      "Laetitia",
      "Mortel",
      "Family Business",
      "Nox",
      "Skam France",
      "Ainsi soient-ils",
      "Les Revenants",
      "Un village français",
      "Hippocrate",
      "Le Bureau des Légendes",
      "Astrid et Raphaëlle",
      "Call My Agent!"
    ]
  },
  {
    "id": "ue",
    "title": "PAYS DE L'UNION EUROPÉENNE",
    "icon": "../assets/Images/histoire.png",
    "question": "Citez un maximum de pays membres de l'Union Européenne.",
    "answers": [
      "Allemagne",
      "Autriche",
      "Belgique",
      "Bulgarie",
      "Chypre",
      "Croatie",
      "Danemark",
      "Espagne",
      "Estonie",
      "Finlande",
      "France",
      "Grèce",
      "Hongrie",
      "Irlande",
      "Italie",
      "Lettonie",
      "Lituanie",
      "Luxembourg",
      "Malte",
      "Pays-Bas",
      "Pologne",
      "Portugal",
      "République tchèque",
      "Roumanie",
      "Slovaquie",
      "Slovénie",
      "Suède"
    ]
  },
  {
    "id": "vinqueurs_grands_chelems_h_et_f",
    "title": "VINQEURS  GRANDS CHELEMS H&F - TENNIS",
    "icon": "assets/Images/geographie.png",
    "question": "VINQEURS  GRANDS CHELEMS H&F - TENNIS",
    "answers": [
      "Novak Djokovic",
      "Rafael Nadal",
      "Roger Federer",
      "Pete Sampras",
      "Andre Agassi",
      "Björn Borg",
      "Rod Laver",
      "Ivan Lendl",
      "John McEnroe",
      "Jimmy Connors",
      "Stefan Edberg",
      "Boris Becker",
      "Andy Murray",
      "Carlos Alcaraz",
      "Jannik Sinner",
      "Serena Williams",
      "Venus Williams",
      "Steffi Graf",
      "Martina Navrátilová",
      "Chris Evert",
      "Margaret Court",
      "Billie Jean King",
      "Monica Seles",
      "Justine Henin",
      "Kim Clijsters",
      "Maria Sharapova",
      "Naomi Osaka",
      "Iga Świątek",
      "Ashleigh Barty",
      "Aryna Sabalenka"
    ]
  }
];
